ifndef TOPDIR
		TOPDIR = $(abspath ../)
endif

include $(TOPDIR)/make_config/com/ColorRules.mk
include $(TOPDIR)/make_config/com/Funcs.mk
include $(TOPDIR)/make_config/com/Flags.mk
include $(TOPDIR)/make_config/ext/Rules.mk

LIBS := mlx_opengl

$(LIBS):
	$(MAKE) -C $@ $(J)

all bonus:
	$(Q)$(call color_printf,$(YELLOW),$(PROJECT_NAME),🎯 Start compiling)
	$(MAKE) $(LIBS)
	$(Q)$(call color_printf,$(GREEN),$(PROJECT_NAME),✨ compiled!)

fclean clean re:
	$(Q)$(foreach dir, $(LIBS), $(MAKE) -C $(dir) $@;)

.PHONY: all clean fclean re bonus $(LIBS)
