ifndef TOPDIR
	TOPDIR := $(abspath ../../)
endif

include $(TOPDIR)/config/makefile/common.mk

DIRS := ConfigValue \
		IParser

LIBS :=	$(wildcard objs/*.o)

include $(TOPDIR)/config/makefile/libRecipes.mk
