ifndef TOPDIR
	TOPDIR := $(abspath ../../)
endif

include $(TOPDIR)/config/makefile/common.mk

DIRS := ExeHandlerFactory \
		IOhandlerFactory

LIBS :=	$(wildcard objs/*.o)

include $(TOPDIR)/config/makefile/libRecipes.mk
